# Heroes Classifier
Disusun guna memenuhi tugas 0.a mata kuliah Pembelajaran Mesin

   * Nama : Hermawan Wiwit N.
   * NIM  : 1301154247
   * Kelas: IF 39-02

In [2]:
import pandas as pd

In [4]:
test = pd.read_csv('test.csv')
test.head()

name  movementSpeed  physicalAttack  armor    hp  mana
0     Layla            270             118     15  2500   424
1   Cyclops            250             107     18  2461   500
2  Minotaur            265             123     25  2705     0
3     Saber            265             121     17  2475   443
4     Roger            235             120     22  2580   450

Membaca file 'test.csv' lalu menampilkan lima data teratas

In [5]:
role= []

In [7]:
for x in range(len(test)):
    if test["movementSpeed"][x]>=270:
        role.append("MARKSMAN")
    elif test["mana"][x]>=500:
        role.append("MAGE")
    elif test["armor"][x]>=25:
        role.append("TANK")
    elif test["physicalAttack"][x]>=121:
        role.append("ASSASSIN")
    elif test["hp"][x]>=2580:
        role.append("FIGHTER")
    else:
        role.append("SUPPORT")

Misinya adalah menentukan, apa peran dari masing-masing hero yang membutuhkan bantuan dari program, dengan aturan sebagai berikut secara berurutan (*hero mendapatkan peran yang paling awal memenuhi syarat*):
1. Heroes yang memiliki movementSpeed >= 270, akan mendapat peran sebagai MARKSMAN (huruf kapital semua)
2. Heroes dengan mana >= 500, akan mendapat peran sebagai MAGE (huruf kapital semua)
3. Heroes dengan armor >= 25, akan mendapat peran sebagai TANK (huruf kapital semua)
4. Heroes dengan physicalAttack >= 121, akan mendapat peran sebagai ASSASSIN (huruf kapital semua)
5. Heroes dengan hp >= 2580, akan mendapat peran sebagai FIGHTER (huruf kapital semua)
6. Heroes lainnya akan mendapat peran sebagai SUPPORT (huruf kapital semua)

Hasil klasifikasi ditampung ke dalam array bernama **'role'**. Jika dikehendaki, array **'role'** yang berisi hasil klasifikasi dapat ditampilakan dengan perintah sebagai berikut (dengan menghilangkan simbol '#'):

In [9]:
#role

In [10]:
prediction = pd.DataFrame({
    "name": test["name"],
    "role": role
})
prediction.to_csv('prediction.csv', index=False)

Pada akhir kondisi, hasil yang ada di dalam array **'role'** dimasukkan ke dalam file **'prediction.csv'**, yang berisi nama hero dan rolenya.

## Terimakasih.